### PR TITLE
Updated github_stats.rb

### PR DESCRIPTION
**Pull request by gwilakers**
Changed "repos" to "repo" on line 15, as it was causing the array to be nil.

### CODE REVIEW

**Comment by gwilakers** [comment]
@cmaujean Any thought into merging this? Thanks!

**Comment by cmaujean** [comment]
I knew i had let something fall to the wayside. I'll get on it

**Comment by gwilakers** [comment]
Not a problem, I figured you just hadn't checked in a while or something. Cheers!

**Comment by cmaujean** [comment]
It looks like the real issue is in the example yaml file, which should look more like this: 

    repos: 
      - dotcloud/docker
      - erikh/ruby-dbi
      - rack/rack
      - torvalds/linux

    login: my_github_user
    password: my_github_password

**Comment by cmaujean** [comment]
I'll push up a change to fix that yml file

**Pull request closed without merging**
